In [16]:
import pandas as pd
import numpy as np
import time
size = 8

In [17]:
def create_board(size):
  chessboard = pd.DataFrame(np.zeros((size, size))).astype(int)
  queens = chessboard.copy()
  queens_vec = size * [0]
  return chessboard, queens, queens_vec

def moves(i, j, action):

  if action == 'add':
    diff = 1
  elif action == 'del':
    diff = -1

  queens.iloc[i][j] += diff
  queens_vec[i] = j

  chessboard.iloc[:][j] += diff
  chessboard.iloc[i][:] += diff
  chessboard.iloc[i][j] -= diff

  k, l = i - 1, j - 1
  m, n = i + 1, j + 1
  o, p = i - 1, j + 1
  q, r = i + 1, j - 1

  while k >= 0 and l >= 0:
    chessboard.iloc[k][l] += diff
    k -= 1
    l -= 1

  while m < size and n < size:
    chessboard.iloc[m][n] += diff
    m += 1
    n += 1

  while o >= 0 and p < size:
    chessboard.iloc[o][p] += diff
    o -= 1
    p += 1

  while q < size and r >= 0:
    chessboard.iloc[q][r] += diff
    q += 1
    r -= 1

In [18]:
chessboard, queens, queens_vec = create_board(size)
start = time.time()
row, column = 0, 0

while row < size:
  ok = 0
  while column < size:
    if chessboard.iloc[row][column] == 0:
      moves(row, column, 'add')
      ok = 1
      break
    column += 1
  if ok == 0:
    row -= 1
    moves(row, queens_vec[row], 'del')
    column = queens_vec[row] + 1
  else:
    row += 1
    column = 0
     

finish = time.time()
print('Execution time: {} seconds'.format(round(finish-start, 2)))
queens

Execution time: 0.41 seconds

   0  1  2  3  4  5  6  7
0  1  0  0  0  0  0  0  0
1  0  0  0  0  1  0  0  0
2  0  0  0  0  0  0  0  1
3  0  0  0  0  0  1  0  0
4  0  0  1  0  0  0  0  0
5  0  0  0  0  0  0  1  0
6  0  1  0  0  0  0  0  0
7  0  0  0  1  0  0  0  0

In [11]:
list = 8 * [8 * [0]]

In [12]:
list

[[0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0]]

In [15]:
list[0][0] = 1
list

[[1, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0]]